name: Learn Jobs and Steps

on:
  push:
    branches:
      - main

jobs:
  learning-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Start
        run: echo "Pipeline started"

      - name: Step 2 - Check system
        run: uname -a

      - name: Step 3 - Finish
        run: echo "Pipeline completed"